title: Testing Github pages...
description: Random tricks with github pages
theme: jekyll-theme-cayman
show_downloads: true
locale: en-US
words_per_minute: 200
repository: dyakonoff/jekyll-test
# baseurl: "http://dyakonoff.github.io/jekyll-test"
baseurl: "github.com/dyakonoff/jekyll-test"
baseimageurl: "github.com/dyakonoff/jekyll-test/blob/master/"
# url: "http://dyakonoff.github.io"